version: '3'
services:
  # React.js - Front-End
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front.dev
    container_name: barai_frontend
    restart: always
    volumes:
      - type: bind
        source: front
        target: /app
    tty:
      true
    ports:
      - 3000:3000

  # ... - Back-End

  # Postgres - Data Base
  database:
    image: postgres:15.4-bullseye
    container_name: barai_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: fidelio
      PGDATA: /data/postgres
    volumes:
       - postgres-db:/data/postgres
    ports:
      - 5432:5432
    networks:
      - app_network

  # DB Adminer
  pgadmin:
    container_name: barai_adminer
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: fidelio
    ports:
      - "5050:80"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres-db:
  front:
  # back:
