version: '3'
services:
  # React.js - Front-End
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: barai_frontend
    restart: always
    volumes: 
      - front:/app
    ports:
      - 4200:8000
    command: >
      npm run dev --host
  
  # Java - Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: barai_backend
    restart: on-failure
    volumes:
      - back:/app
    # command: >
    ports:
      - 8000:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mariadb://database:3306/barai_db?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "fidelio",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.jpa.hibernate.dialect" : "org.hibernate.dialect.MYSQL5InnoDBDialect"
      }'
    depends_on:
      - database
    networks:
      - app_network
    # PHP Debug Extra Host  
    # extra_hosts:
    #     - host.docker.internal:host-gateway

  # MariaDB - Data Base
  database:
    image: docker.io/bitnami/mariadb:10.6.11
    container_name: barai_db
    restart: unless-stopped
    volumes:
      - database:/var/lib/mysql
    ports:
      - 4000:3306
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      MARIADB_ROOT_PASSWORD: fidelio
      MARIADB_DATABASE: barai_db
    networks:
      - app_network

  # DB Adminer
  adminer:
    image: adminer:4.8.1-fastcgi
    container_name: barai_adminer
    restart: always
    ports:
      - 9000:80
    environment:
      - PMA_HOST=database
    depends_on:
      - database
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  database:
  front:
  back:
