version: '3'
services:
  # React.js - Front-End
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: barai_frontend
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./front:/app
    command: >
      npm install
  
  # Java - Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: barai_backend
    restart: unless-stopped
    # command: >
    ports:
      - 8000:8000
    environment:
      # - DB_HOST=
      - DB_PORT=4000
      - DB_USERNAME=root
      - DB_DATABASE=database
    volumes:
      - './back:/var/www'
    depends_on:
      - mariadb
    networks:
      - app_network
    # PHP Debug Extra Host  
    # extra_hosts:
    #     - host.docker.internal:host-gateway

  # MariaDB - Data Base
  database:
    image: docker.io/bitnami/mariadb:10.6.11
    container_name: barai_db
    restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - 4000:3306
    expose:
      - 4000
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      MARIADB_ROOT_PASSWORD: fidelio
    networks:
      - app_network

  # DB Adminer
  adminer:
    image: adminer:4.8.1-fastcgi
    container_name: barai_adminer
    restart: always
    ports:
      - 9000:80
    environment:
      - PMA_HOST=mariadb
    depends_on:
      - database
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  database: