version: '3'
services:
  # Vue.js - Front-End
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: kgb_frontend
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./front:/app
      
  # Laravel - Backend
  laravel:
    image: docker.io/bitnami/laravel:9.5.2-debian-11-r1
    container_name: kgb_backend
    restart: unless-stopped
    command: >
      # sh -c "apt update \
        # apt -qy install $PHPIZE_DEPS \
        # apt -qy install autoconf \
        # curl -sSL https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions \
        # install-php-extensions gd xdebug 
        # pecl channel-update pecl.php.net"
    ports:
      - 8000:8000
    environment:
      # - DB_HOST=
      - DB_PORT=4000
      - DB_USERNAME=root
      - DB_DATABASE=mariadb
    volumes:
      - './back:/app'
    depends_on:
      - mariadb
    networks:
      - app_network
    # PHP Debug Extra Host  
    # extra_hosts:
    #     - host.docker.internal:host-gateway

  # MariaDB - Data Base - Backend
  mariadb:
    image: docker.io/bitnami/mariadb:10.6.11
    container_name: kgb_db
    restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - 4000:3306
    expose:
      - 4000
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      MARIADB_ROOT_PASSWORD: fidelio
    networks:
      - app_network

  # PHP My Admin
  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    container_name: kgb_phpmyadmin
    restart: always
    ports:
      - 9000:80
    environment:
      - PMA_HOST=mariadb
    depends_on:
      - mariadb
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mariadb: