version: '3'
services:
  # React.js - Front-End
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front.dev
    container_name: barai_frontend
    restart: always
    volumes:
      - type: bind
        source: front
        target: /app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  # ... - Back-End
  backend:
    depends_on:
      - database
    container_name: barai-backend
    ports:
      - 8080:80
    build: 
      context: ./back
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=User ID=root;Password=fidelio;Server=database;Port=5432;Database=barai; IntegratedSecurity=true;Pooling=true;
      - ASPNETCORE_URLS=http://+:80
    networks:
      - app_network

  # Postgres - Data Base
  database:
    image: postgres:15.4-bullseye
    container_name: barai_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: fidelio
      POSTGRES_DB: barai
      PGDATA: /data/postgres
    volumes:
       - postgres-db:/data/postgres
    ports:
      - 5432:5432
    networks:
      - app_network

  # DB Adminer
  pgadmin:
    container_name: barai_adminer
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: fidelio
    ports:
      - "5050:80"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres-db:
  front:
  back:
